/*
 * app_states.h
 *
 *  Created on: Dec 4, 2025
 *      Author: admin
 */

#ifndef APP_STATES_H_
#define APP_STATES_H_

#include "main.h"

#include "hsm_timer.h"
#include "hsm.h"
#include "ee.h"
#include "Modbus.h"


#define MB_COM_UART	huart2
#define MB_BAT_UART	huart3


#define MB_COM_PORT	RS4851_TXEN_GPIO_Port
#define MB_COM_PIN	RS4851_TXEN_Pin
#define MB_BAT_PORT	RS4852_TXEN_GPIO_Port
#define MB_BAT_PIN	RS4852_TXEN_Pin

#define SETTING_WAIT_DONE_MS		5000
#define LED_STATUS_ON_MS			100



typedef enum {
	LED_OFF = GPIO_PIN_RESET,
	LED_ON = GPIO_PIN_SET,
} LED_State_t;

typedef enum {
	LS_ACTIVE = GPIO_PIN_RESET,
	LS_IDLE = GPIO_PIN_SET,
} LS_State_t;

typedef enum {
	SLOT_EMPTY = 0,
	SLOT_FULL,
} Slot_State_t;

typedef enum {
	CHRG_OFF = GPIO_PIN_RESET,
	CHRG_ON = GPIO_PIN_SET,
} Charge_Control_State_t;

typedef enum {
	EM_PASSTIVE = GPIO_PIN_RESET,
	EM_ACTIVE = GPIO_PIN_SET,
} Emergency_State_t;

typedef enum {
	HSME_LOOP = HSME_START,

	HSME_SET_INVALID_BAUD,
	HSME_SET_BAUD_CHANGE_VALUE,

	HSME_SWITCH_LIMIT_ACTIVE,
	HSME_SWITCH_LIMIT_PASSTIVE,
	HSME_BAT_RECEIVED_OK,
	HSME_BAT_RECEIVED_TIMEOUT,
	HSME_COMM_RECEIVED_OK,

	HSME_CUSTOM_TICK_UPDATE,
	HSME_TURN_OFF_LED_STT_TICK_UPDATE,
	HSME_SETTING_DONE_TICK_UPDATE,
} HSMEvent_t;

typedef enum {
	BAT_REG_BMS_STATE = 0,
	BAT_REG_CTRL_REQUEST,
	BAT_REG_CTRL_RESPONSE,
	BAT_REG_FET_CTRL_PIN,
	BAT_REG_FET_STATUS,
	BAT_REG_ALARM_BITS,
	BAT_REG_FAULTS,
	BAT_REG_PACK_VOLT,
	BAT_REG_STACK_VOLT,
	BAT_REG_PACK_CURRENT_HIGH,
	BAT_REG_PACK_CURRENT_LOW,
	BAT_REG_ID_VOLT,
	BAT_REG_TEMP1_HIGH,
	BAT_REG_TEMP1_LOW,
	BAT_REG_TEMP2_HIGH,
	BAT_REG_TEMP2_LOW,
	BAT_REG_TEMP3_HIGH,
	BAT_REG_TEMP3_LOW,
	BAT_REG_CELL1,
	BAT_REG_CELL2,
	BAT_REG_CELL3,
	BAT_REG_CELL4,
	BAT_REG_CELL5,
	BAT_REG_CELL6,
	BAT_REG_CELL7,
	BAT_REG_CELL8,
	BAT_REG_CELL9,
	BAT_REG_CELL10,
	BAT_REG_CELL11,
	BAT_REG_CELL12,
	BAT_REG_CELL_NONE_1,
	BAT_REG_CELL_NONE_2,
	BAT_REG_CELL_NONE_3,
	BAT_REG_CELL13,
	BAT_REG_SAFETY_A,
	BAT_REG_SAFETY_B,
	BAT_REG_SAFETY_C,
	BAT_REG_ACCU_INT_HIGH,
	BAT_REG_ACCU_INT_LOW,
	BAT_REG_ACCU_FRAC_HIGH,
	BAT_REG_ACCU_FRAC_LOW,
	BAT_REG_ACCU_TIME_HIGH,
	BAT_REG_ACCU_TIME_LOW,
	BAT_REG_PIN_PERCENT,
	BAT_REG_PERCENT_TARGET,
	BAT_REG_CELL_RESISTANCE,
	BAT_REG_SOC_PERCENT,
	BAT_REG_SOH_VALUE,
	BAT_REG_CAPACITY,
	BAT_REG_SINGLE_PARALLEL,
	BAT_REG_BMS_STATE_2,
	TOTAL_BAT_REGISTERS,
} BatertyRegister_t;

typedef enum {
	REG_STA_BMS_STATE = 0,
	REG_STA_CTRL_REQUEST,
	REG_STA_CTRL_RESPONSE,
	REG_STA_FET_CTRL_PIN,
	REG_STA_FET_STATUS,
	REG_STA_ALARM_BITS,
	REG_STA_FAULTS,
	REG_STA_PACK_VOLT,
	REG_STA_STACK_VOLT,
	REG_STA_PACK_CURRENT_HIGH,
	REG_STA_PACK_CURRENT_LOW,
	REG_STA_ID_VOLT,
	REG_STA_TEMP1_HIGH,
	REG_STA_TEMP1_LOW,
	REG_STA_TEMP2_HIGH,
	REG_STA_TEMP2_LOW,
	REG_STA_TEMP3_HIGH,
	REG_STA_TEMP3_LOW,
	REG_STA_CELL1,
	REG_STA_CELL2,
	REG_STA_CELL3,
	REG_STA_CELL4,
	REG_STA_CELL5,
	REG_STA_CELL6,
	REG_STA_CELL7,
	REG_STA_CELL8,
	REG_STA_CELL9,
	REG_STA_CELL10,
	REG_STA_CELL11,
	REG_STA_CELL12,
	REG_STA_CELL_NONE_1,
	REG_STA_CELL_NONE_2,
	REG_STA_CELL_NONE_3,
	REG_STA_CELL13,
	REG_STA_SAFETY_A,
	REG_STA_SAFETY_B,
	REG_STA_SAFETY_C,
	REG_STA_ACCU_INT_HIGH,
	REG_STA_ACCU_INT_LOW,
	REG_STA_ACCU_FRAC_HIGH,
	REG_STA_ACCU_FRAC_LOW,
	REG_STA_ACCU_TIME_HIGH,
	REG_STA_ACCU_TIME_LOW,
	REG_STA_PIN_PERCENT,
	REG_STA_PERCENT_TARGET,
	REG_STA_CELL_RESISTANCE,
	REG_STA_SOC_PERCENT,
	REG_STA_SOH_VALUE,
	REG_STA_CAPACITY,
	REG_STA_SINGLE_PARALLEL,
	REG_STA_BMS_STATE_2,

	REG_STA_IS_PIN_IN_SLOT,
	REG_STA_IS_PIN_TIMEOUT,
	REG_STA_IS_EMERGENCY_STOP,
	REG_STA_CHRG_CTRL,

	TOTAL_STA_REGISTERS,
} StationRegister_t;
typedef enum {
	TELE_MASTER_READ_FULL_BAT_DATA = 0,
	TOTAL_TELE_MASTER,
} TelegramMaster_t;

typedef struct {
	uint8_t baudrate;
	uint16_t magic;
} Storage_t;

typedef struct {
	HSM parent;

	uint8_t modbus_address;

	modbusHandler_t handlerModbusMaster;
	uint16_t dataModbusMaster[TOTAL_BAT_REGISTERS];
	modbus_t telegramMaster[TOTAL_TELE_MASTER];


	modbusHandler_t handlerModbusSlave;
	uint16_t dataModbusSlave[TOTAL_STA_REGISTERS];


	Storage_t storage;
} DeviceHSM_t;




void app_states_hsm_init(DeviceHSM_t *me);

void default_parameter_init(DeviceHSM_t* hsm);

uint32_t BaudrateCodeToValue(uint8_t code);
uint8_t BaudrateValueToCode(uint32_t baudrate);
HAL_StatusTypeDef UART_Reconfigure(UART_HandleTypeDef *huart, uint32_t baudrate);
HAL_StatusTypeDef UART_ReconfigureByCode(UART_HandleTypeDef *huart, uint8_t code);



#endif /* APP_STATES_H_ */
